backend:
  name: git-gateway
  branch: main
media_folder: "static/images"  # Where uploaded images go
public_folder: "/images"       # Public URL for images
collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "layouts/index.html"
        label: "Home"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string", default: "irgenius Shop"}
          - {label: "Body", name: "body", widget: "markdown", default: "<h1>Welcome to irgenius Shop</h1><p>More coming soon...</p>"}